### PR TITLE
Export FetchCookieImpl and update esbuild version

### PR DESCRIPTION
**Pull request by piwonskp**
FetchCookieImpl is not exported which causes fail during generation of .d.ts files for packages using fetch-cookie

### CODE REVIEW

**Comment by piwonskp** [comment]
@valeriangalliat during `npm install` the error occurs:
```
src/utils/fetchPonyfill.ts(4,1): error TS4082: Default export of the module has or is using private name 'FetchCookieImpl'.

Error: error occured in dts build
    at Worker.<anonymous> (/workspaces/starknet.js/node_modules/tsup/dist/index.js:2281:26)
    at Worker.emit (node:events:514:28)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
DTS Build error
RollupError: Failed to compile. Check the logs above.
    at error (/workspaces/starknet.js/node_modules/rollup/dist/shared/rollup.js:353:30)
    at Object.error (/workspaces/starknet.js/node_modules/rollup/dist/shared/rollup.js:1721:20)
    at Object.error (/workspaces/starknet.js/node_modules/rollup/dist/shared/rollup.js:25627:42)
    at generateDtsFromTs (/workspaces/starknet.js/node_modules/tsup/dist/rollup.js:7498:22)
    at /workspaces/starknet.js/node_modules/tsup/dist/rollup.js:7505:59
    at _nullishCoalesce (/workspaces/starknet.js/node_modules/tsup/dist/rollup.js:1:198)
    at Object.transform (/workspaces/starknet.js/node_modules/tsup/dist/rollup.js:7505:18)
    at /workspaces/starknet.js/node_modules/rollup/dist/shared/rollup.js:1914:40
npm ERR! code 1
npm ERR! path /workspaces/starknet.js
npm ERR! command failed
npm ERR! command sh -c npm run build && husky install
```
During test:
```
node_modules/fetch-cookie/cjs/index.d.ts:42:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

42 export = fetchCookie;
```

**Comment by valeriangalliat** [comment]
I can successfully install (and `npm run build`) that project using the current version of fetch-cookie

image


`npm run ts:check` also succeeds 

I can't run `npm test` because I don't have a devnet running but based on the above I think it should be fine?

Let me know if you can try again with fetch-cookie 2.2.0 on your side and see if this still happens? :)

**Comment by piwonskp** [comment]
@valeriangalliat `npm run build` doesn't work for me:
```
npm run build

> starknet@6.1.1 build
> tsup && npm run build:esm && npm run build:iife && npm run build:dts

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Using tsup config: /workspaces/starknet.js/tsup.config.ts
CLI Target: es2022
CLI Cleaning output folder
CJS Build start
CJS dist/index.js     195.80 KB
CJS dist/index.js.map 442.79 KB
CJS ⚡️ Build success in 81ms

> starknet@6.1.1 build:esm
> tsup --clean false --format esm --platform node

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Using tsup config: /workspaces/starknet.js/tsup.config.ts
CLI Target: es2022
ESM Build start
ESM dist/index.mjs     191.51 KB
ESM dist/index.mjs.map 442.34 KB
ESM ⚡️ Build success in 76ms

> starknet@6.1.1 build:iife
> tsup --clean false --format iife --platform browser

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Using tsup config: /workspaces/starknet.js/tsup.config.ts
CLI Target: es2022
IIFE Build start
IIFE dist/index.global.js     796.25 KB
IIFE dist/index.global.js.map 1.50 MB
IIFE ⚡️ Build success in 160ms

> starknet@6.1.1 build:dts
> tsup --clean false --dts-only

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Using tsup config: /workspaces/starknet.js/tsup.config.ts
DTS Build start
src/utils/fetchPonyfill.ts(4,1): error TS4082: Default export of the module has or is using private name 'FetchCookieImpl'.

Error: error occured in dts build
    at Worker.<anonymous> (/workspaces/starknet.js/node_modules/tsup/dist/index.js:2281:26)
    at Worker.emit (node:events:514:28)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
DTS Build error
RollupError: Failed to compile. Check the logs above.
    at error (/workspaces/starknet.js/node_modules/rollup/dist/shared/rollup.js:353:30)
    at Object.error (/workspaces/starknet.js/node_modules/rollup/dist/shared/rollup.js:1721:20)
    at Object.error (/workspaces/starknet.js/node_modules/rollup/dist/shared/rollup.js:25627:42)
    at generateDtsFromTs (/workspaces/starknet.js/node_modules/tsup/dist/rollup.js:7498:22)
    at /workspaces/starknet.js/node_modules/tsup/dist/rollup.js:7505:59
    at _nullishCoalesce (/workspaces/starknet.js/node_modules/tsup/dist/rollup.js:1:198)
    at Object.transform (/workspaces/starknet.js/node_modules/tsup/dist/rollup.js:7505:18)
    at /workspaces/starknet.js/node_modules/rollup/dist/shared/rollup.js:1914:40
 ```
 
Npm version I'm using:
```
npm --version
10.2.3
$ node --version
v20.10.0
```

**Comment by piwonskp** [comment]
Maybe you've got a typescript version installed globally that is being used during build? `tsc --version` returns 5.3.3 for me

**Comment by valeriangalliat** [comment]
I managed to repro!

OK so looks like tsup in order to generate type definitions, first compiles the .d.ts using tsc for each and every source file, even if it ends up discarding those at the end to keep only what's exported by the final bundle...

So that intermediary phase wants to compile `dist/utils/fetchPonyfill.d.ts` into

```ts
import makeFetchCookie from 'fetch-cookie';
declare const _default: typeof fetch | makeFetchCookie.FetchCookieImpl<RequestInfo | URL, RequestInit, Response>;
export default _default;
```

Which indeed requires FetchCookieImpl to be exported.

Even if afterwards it just discards that file anyway because the bundled code doesn't actually expose FetchCookieImpl 😅 

---

The part with changing the CJS index-wrapper exports is a breaking change however as package will need to be imported with `const fetchCookie = require('fetch-cookie').default` as opposed to `const fetchCookie = require('fetch-cookie')` as is currently the case, so I'll have to bump a major version for that... I think it's the way forward though and it makes ESM interop easier anyway

**Pull request merged**
